execute_process(COMMAND "${CMAKE_COMMAND}" --build "${FAIO_BUILD_DIR}" --target "${FAIO_FAILURE_TARGET}" --parallel 1
    RESULT_VARIABLE _faio_result OUTPUT_VARIABLE _faio_output ERROR_VARIABLE _faio_error)
set(_faio_diagnostic "${_faio_output}\n${_faio_error}")
file(MAKE_DIRECTORY "${FAIO_BUILD_DIR}/experimental-evidence")
file(WRITE "${FAIO_BUILD_DIR}/experimental-evidence/${FAIO_FAILURE_TARGET}.log" "${_faio_diagnostic}")
if(_faio_result EQUAL 0)
    message(FATAL_ERROR "Expected compilation failure, but ${FAIO_FAILURE_TARGET} succeeded")
endif()
if(DEFINED FAIO_FAILURE_PATTERN AND NOT _faio_diagnostic MATCHES "${FAIO_FAILURE_PATTERN}")
    message(FATAL_ERROR "Compilation failed without expected diagnostic '${FAIO_FAILURE_PATTERN}': ${_faio_diagnostic}")
endif()
if(NOT _faio_diagnostic MATCHES "(error:|Error:|multiple definition|undefined reference)")
    message(FATAL_ERROR "Failure was not a C++ compile/link diagnostic: ${_faio_diagnostic}")
endif()
